name: counselling_gurus
description: A new Flutter project.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.7.2 <3.0.0"

dependencies:
  feature_discovery: ^0.12.0
  wiredash: ^0.1.0
  flutter_branch_sdk: ^0.5.0
  google_fonts: ^1.0.0
  share: ^0.6.4
  assorted_layout_widgets: ^1.1.1
  percent_indicator: ^2.1.1
  url_launcher: ^5.4.5
  flutter_plugin_pdf_viewer: ^1.0.7
  autocomplete_textfield: ^1.7.3
  file_picker: ^1.13.0+1
  toast: ^0.1.5
  pie_chart: ^3.1.1
  flutter:
    sdk: flutter
  simple_animations: ^2.2.0

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2
  http: any
  bottom_navy_bar: ^5.4.0
  titled_navigation_bar: ^4.1.0
  shared_preferences: ^0.5.7+1
  flip_card: ^0.4.4
  flutter_swiper: any
  table_calendar: ^2.2.3
  swipedetector: ^1.2.0
  youtube_player_flutter: ^7.0.0+7
  scoped_model: ^1.0.1
  flutter_socket_io: ^0.6.0
  giffy_dialog: ^1.8.0


dev_dependencies:
  flutter_launcher_icons: "^0.7.3"
  flutter_test:
    sdk: flutter

  camera:
  path_provider:
  path:
#  image_picker: ^0.6.6+1
  fluttertoast: ^4.0.0



# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/app_logo.png"


flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/splashpic.png
    - assets/images/college-blog-temp.png
    - assets/images/app_logo.png
    - assets/images/background.png
    - assets/images/background2.png
    - assets/images/college.png
    - assets/images/profile.png
    - assets/images/hugo-customer-support.png
    - assets/images/hugo-waiting.png
    - assets/images/hugo-list-is-empty.png
    - assets/images/new1.png
    - assets/images/new2.png
    - assets/images/new3.png
    - assets/images/new4.png
    - assets/images/SplashScreen.png
    - assets/images/LoginOptions.png
    - assets/images/Notes.png
    - assets/images/giphy.gif
    - assets/images/m-blog-1.png
    - assets/images/m-blog-2.jpg
    - assets/images/m-blog-3.jpg
    - assets/images/m-blog-4.jpg
    - assets/images/m-blog-5.jpg
    - assets/images/m-blog-6.jpg
    - assets/images/first.png



      #  - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages

